name: Sync Labels from Central Repository

on:
  repository_dispatch:
    types:
      - sync_labels

jobs:
  call-reusable-workflow:
    uses: SchemaApp/SchemaApp/.github/workflows/sync-labels.yml@master
    with:
      labels_url: ${{ github.event.client_payload.labels_url }}
